---

- name: Set up postgres
  hosts: localhost
  user: ubuntu
  become: true
  gather_facts: false
  vars:
    postgres_root_user: ubuntu
    postgres_root_pass: mypassword
    postgres_db_name: my_db
    allow_world_readable_tmpfiles: true

  roles:
    - setup-postgres