---

- name: Set up postgres
  hosts: localhost
  remote_user: ubuntu
  become: true
  gather_facts: false
  vars:
    postgres_root_user: ubuntu
    postgres_root_pass: mypassword
    postgres_db_name: my_db
    allow_world_readable_tmpfiles: true

  pre_tasks:
    - name: Allow user sudo without a password
      lineinfile:
        path: /etc/sudoers
        state: present
        line: 'sudo ALL=(ALL) NOPASSWD: ALL'
        validate: 'visudo -cf %s'

  roles:
    - setup-postgres

  handlers:
      # Set up handlers
      # include_tasks: postgres_handlers.yml
      - name: Restart Postgresql
        systemd:
          name: postgresql
          state: restarted

      - name: Start Postgresql
        systemd:
          name: postgresql
          state: started

      - name: Stop Postgresql
        systemd:
          name: postgresql
          state: stopped

      - name: Enable Postgresql
        systemd:
          name: postgresql
          enabled: yes