---

- name: Make directory
  file:
    path: ~/project
    state: directory

- name: Copy files
  unarchive:
    src: ~/project/artifact.tar.gz
    dest: ~/project


- name: List files in directory
  shell: |
    pwd
    ls
    cd ~/project
    pwd
  args:
    executable: /bin/bash
  register: shell_result

- name: Show results
  debug:
    msg: "{{ shell_result.stdout_lines }}"
