---

- name: Make directory
  file:
    path: /home/ubuntu/backend
    state: directory

- name: Print Env Vars
  shell: |
    printenv
    printenv > /home/ubuntu/backend/.env
    cat /home/ubuntu/backend/.env
  register: env_result

- name: show proj vars
  debug:
    msg: " This is shell {{ SHELL }}"


- name: Copy files
  unarchive:
    src: ../../artifact.tar.gz
    dest: /home/ubuntu/backend

- name: List files in directory
  shell: |
    echo "This is the home dir: $(echo ~/)"
    echo "HOME DIR: $(echo ${HOME})"
    echo "This is the pwd: $(pwd)"
    cd /home/ubuntu/backend
    echo "This is the working dir after cd : $(pwd)"
    echo "This is the listed project directory: $(ls)"
  args:
    executable: /bin/bash
  register: shell_result

- name: Show results
  debug:
    msg: "{{ shell_result.stdout_lines }}"

- name: Environment result
  debug:
    msg: "{{ env_result.stdout_lines }}"


