---

- name: Make directory
  file:
    path: ~/project
    state: directory
  register: directory_out

- name: Print Env Vars
  shell: |
    printenv
    printenv >> ~/project/.env
    cat ~/project/.env
  register: env_result


- name: Copy files
  unarchive:
    src: ../../artifact.tar.gz
    dest: ~/project

- name: List files in directory
  shell: |
    echo "This is the home dir: $(echo ~/)"
    echo "This is the pwd: $(pwd)"
    echo "This is the listed directory: $(ls)"
    cd ~/project
    echo "This is the working dir after cd ~/project: $(pwd)"
  args:
    executable: /bin/bash
  register: shell_result

- name: Show results
  debug:
    msg: "{{ shell_result.stdout_lines }}"

- name: Directory result
  debug:
    msg: "{{ directory_out.stout_lines }}"

- name: Environment result
  debug:
    msg: "{{ env_result.stdout_lines }}"


