---

- name: Make directory
  file:
    path: /home/ubuntu/backend
    state: directory
  register: directory_out

- name: Print Env Vars
  shell: |
    printenv
    printenv >> ~/project/.env
    cat ~/project/.env
  register: env_result


- name: Copy files
  unarchive:
    src: ../../artifact.tar.gz
    dest: /home/ubuntu/project

- name: List files in directory
  shell: |
    echo "This is the home dir: $(echo ~/)"
    echo "This is the pwd: $(pwd)"
    cd /home/ubuntu/project
    echo "This is the working dir after cd : $(pwd)"
    echo "This is the listed project directory: $(ls)"
  args:
    executable: /bin/bash
  register: shell_result

- name: Show results
  debug:
    msg: "{{ shell_result.stdout_lines }}"

- name: Directory result
  debug:
    msg: "{{ directory_out.stdout_lines }}"

- name: Environment result
  debug:
    msg: "{{ env_result.stdout_lines }}"


