---

- name: Make directory
  file:
    path: ~/project
    state: directory

- name: Copy files
  unarchive:
    src: ~/project/artifact.tar.gz
    dest: ~/project

- name: List files in directory
  shell: |
    cat backend.yml
  args:
    chdir: ~/project/
    executable: /bin/bash