---

- name: Make directory
  file:
    path: ~/project
    state: directory

- name: Copy files
  unarchive:
    src: ./artifact.tar.gz
    dest: ~/project

- name: List files in directory
  shell: |
    pwd
    ls
  args:
    executable: /bin/bash