version: 2.1

jobs:
  test-1:
    docker:
      - image: circleci/node:13.8.0
    
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            sudo apt install python3-pip
            pip3 --version
            pip3 install awscli
            sudo apt-get -y install gzip tar


workflows:
  test-workflow:
    jobs:
      - test-1


