version: 2.1

jobs:
  test-1:
    docker:
      - image: circleci/node:13.8.0
    
    steps:
      - checkout
      - run:
          name: update inventory.txt file
          command: |
            pwd | cat >> .circleci/ansible.inventory.txt
            cat .circleci/ansible.inventory.txt
      - persist_to_workspace:
          root: ~/
          path: project/.circleci/ansible.inventory.txt
    
  test-2:
    docker:
      - image: circleci/node:13.8.0

    steps:
        - checkout
        - attach_workspace:
          at: ~/
        - run:
            name: Check if file was updated
            command: |
              cat .circleci/ansible.inventory.txt


workflows:
  test-workflow:
    jobs:
      - test-1


