version: 2.1

jobs:
  docker:
    - image: circleci/node:13.8.0
  
  steps:
    - checkout
    - run:
        name: Install dependencies
        command: |
          apt update
          apt install python3-pip
          pip3 --version
          pip install awscli


