version: 2.1

jobs:
  test-1:
    docker:
      - image: circleci/node:13.8.0
    
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            pwd
            echo ~


workflows:
  test-workflow:
    jobs:
      - test-1


